raw_data_path: "../data/raw_data.csv"
cleaned_data_path: "../data/cleaned_data.csv"
test_size: 0.3
random_state: 42
columns_to_drop: ["instant", "dteday", "casual", "registered", "atemp"]
category_columns: ["season", "yr", "mnth", "holiday", "weekday", "workingday", "weathersit"]
cat_columns_to_encode: ["season", "mnth", "weekday", "weathersit"]
numerical_columns: ["temp", "hum", "windspeed"]
target_column: "cnt"
weathersit_labels:
  1: "clear"
  2: "cloudy"
  3: "light snow/rain"
  4: "heavy rain"

# As per calendar of 2018 , 01-01-2018 was a monday i.e weekday = 6 as per data dictionary.
weekday_labels:
  0: "tuesday"
  1: "wednesday"
  2: "thursday"
  3: "friday"
  4: "saturday"
  5: "sunday"
  6: "monday"

mnth_labels:
  1: "january"
  2: "february"
  3: "march"
  4: "april"
  5: "may"
  6: "june"
  7: "july"
  8: "august"
  9: "september"
  10: "october"
  11: "november"
  12: "december"

season_labels:
  1: "spring"
  2: "summer"
  3: "fall"
  4: "winter"